project:
  type: website

website:
  title: "my_global_blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

comments:
  giscus:
    repo: IanniMuliterno/my_global_blog